name: gsm_mall
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  firebase: ^7.3.0
  cloud_firestore: ^0.13.7
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  
  cupertino_icons: ^0.1.2
  carousel_pro: ^1.0.0
  flutter_swiper : ^1.1.6
  carousel_slider: ^1.3.0
  badges: ^1.1.0
  http: ^0.12.0+2
  font_awesome_flutter: ^8.5.0
  fluttertoast: ^3.1.3
  custom_radio: ^0.1.2
  flutter_rating_bar: ^3.0.0
  page_transition: "^1.1.5"
  flutter_spinkit: ^3.1.0
  fancy_on_boarding: ^1.6.0
  eva_icons_flutter:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/logo/stylo_logo.jpg"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/
   - assets/logo/
   - assets/home_slider/
   - assets/safety_checklist/
   - assets/logo/stylo_logo.jpg
   - assets/top_category/
   - assets/summer_edit/
   - assets/explore_brands/
   - assets/kids_apparels/
   - assets/category_page_slider/
   - assets/category_explore_category/
   - assets/in_the_spotlight/
   - assets/products/
   - assets/payment_icon/
   - assets/onboarding_images/
   - assets/user_profile/
   - assets/search/
   - assets/json/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Francois One
      fonts:
        - asset: fonts/FrancoisOne-Regular.ttf
          weight: 400
    - family: Alatsi
      fonts:
        - asset: fonts/Alatsi-Regular.ttf
          weight: 400
    - family: Kaushan Script
      fonts:
        - asset: fonts/KaushanScript-Regular.ttf
          weight: 400
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
          weight: 400
    - family: Jost
      fonts:
        - asset: fonts/Jost-VariableFont_wght.ttf
          weight: 400

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
module:
  androidX: true